<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-14T11:02:01 GMT-07:00" name="Suite" finished-at="2023-09-14T11:02:35 GMT-07:00" duration-ms="33727">
    <groups>
    </groups>
    <test started-at="2023-09-14T11:02:01 GMT-07:00" name="testng" finished-at="2023-09-14T11:02:35 GMT-07:00" duration-ms="33727">
      <class name="TestCases.verifySignup">
        <test-method is-config="true" signature="launchURL()[pri:0, instance:TestCases.verifySignup@54d9d12d]" started-at="2023-09-14T11:02:01 GMT-07:00" name="launchURL" finished-at="2023-09-14T11:02:15 GMT-07:00" duration-ms="13429" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchURL -->
        <test-method signature="signup()[pri:0, instance:TestCases.verifySignup@54d9d12d]" started-at="2023-09-14T11:02:15 GMT-07:00" name="signup" finished-at="2023-09-14T11:02:26 GMT-07:00" duration-ms="11486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup -->
      </class> <!-- TestCases.verifySignup -->
      <class name="TestCases.VerifyLogin">
        <test-method is-config="true" signature="launchURL()[pri:0, instance:TestCases.VerifyLogin@1a677343]" started-at="2023-09-14T11:02:26 GMT-07:00" name="launchURL" finished-at="2023-09-14T11:02:34 GMT-07:00" duration-ms="7768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchURL -->
        <test-method signature="login()[pri:0, instance:TestCases.VerifyLogin@1a677343]" started-at="2023-09-14T11:02:34 GMT-07:00" name="login" finished-at="2023-09-14T11:02:35 GMT-07:00" duration-ms="935" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Please check your password. If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please check your password. If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at Resources.CommonUtilities.handleAssertions(CommonUtilities.java:33)
at TestCases.VerifyLogin.login(VerifyLogin.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- TestCases.VerifyLogin -->
    </test> <!-- testng -->
  </suite> <!-- Suite -->
</testng-results>
